config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :students
    resources :teachers
    resources :pictures
    resources :galleries
    resources :postulations
    resources :comments
    resources :postuling_teachers
    resources :lessons
    resources :topics
    resources :topic_groups
    resources :level
    resources :advert_prices
    resources :adverts
    resources :payments

    

    get "/user_conversation/:id", to: "users#show_conversation", as: 'show_conversation'
    
   
    # Gestion des serveurs BBB depuis l'admin
    resources :bigbluebutton_servers
    resources :bigbluebutton_recordings
    resources :bbb_rooms

    root to: "users#index"
  end
  resources "contact", only: [:new, :create]
    


  scope '/user/mangopay', controller: :payments do
  end

  scope '/user/mangopay', controller: :wallets do
    get "edit_wallet" => :edit_mangopay_wallet
    put "edit_wallet" => :update_mangopay_wallet
    get "index_wallet" => :index_mangopay_wallet
    get "direct_debit" => :direct_debit_mangopay_wallet
    put "direct_debit" => :load_wallet
    get "transactions" => :transactions_mangopay_wallet
    get "card_info" => :card_info
    put "send_card_info" => :send_card_info
    get 'bank_accounts' => :bank_accounts
    put 'update_bank_accounts' => :update_bank_accounts
    get 'payout' => :payout
    put 'make_payout' => :make_payout
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations=> "registrations" }

  resources :users, only: [:update] do
    patch 'crop' => 'users#crop'
    post 'crop' => 'users#crop'
  end

  get 'dashboard' => 'dashboards#index', :as => 'dashboard'
  get 'featured_reviews' => 'reviews#featured_reviews'

  resources :users, :only => [:show] do
    resources :require_lesson
    put '/lesson_requests/payment' => 'lesson_requests/payment'
    resources :lesson_requests, only: [:new, :create] do
      get 'topics/:topic_group_id', action: :topics, on: :collection
      get 'levels/:topic_id', action: :levels, on: :collection
      post :calculate, on: :collection
      get :credit_card_process, on: :collection
      get :bancontact_process, on: :collection
      post :create_account, on: :collection
    end
    resources :reviews, only: [:index, :create, :new]
  end
  get '/both_users_online' => 'users#both_users_online', :as => 'both_users_online'
  authenticated :user do
    root 'dashboards#index'
  end
  resources :topics do
    get :autocomplete_topic_title, :on => :collection
  end
  match "/profs/" => "users#profs_by_topic", as: :profs, via: :post
  match "/profs/:topic" => "users#index", :as => :profs_by_topic, :via => [:get]
  get "/profs" => "users#index"

  unauthenticated :user do
    devise_scope :user do
      get "/" => "pages#index"
    end
  end
  resources :galleries, only: [:update, :edit, :show]
  resources :pictures, only: [:new, :destroy, :show]
  resources :degrees
  resources :notifications
  get "/notifications/unread/" => "notifications#number_of_unread"

  resources :adverts do
    resources :advert_prices
  end

  get '/adverts_user/:user_id', to: 'adverts#get_all_adverts', as: 'get_all_adverts'

  get "/pages/*page" => "pages#show"
  resources :pages do

  end
  get '/become_teacher/accueil' => "pages#devenir-prof"
  get '/index' => "pages#index"
  resources :become_teacher
  resources :conversations, only: [:index, :show, :delete] do
    member do
      post :reply
      post :mark_as_read
      post :trash
      post :mark_as_unread
      post :untrash
    end
  end
  match 'mailbox' => 'conversations#index', :as => 'messagerie', via: :get
  match 'mailbox/:mailbox' => 'conversations#index', :as => 'mailbox', via: :get
  post 'mailbox/search' => 'conversations#search'

  #Permet affichage facture
  get "/payments/index" => "payments#index"
  
  #post "lessons/:teacher_id/require_lesson", to: "lessons#require_lesson", as: 'require_lesson'
  resources :lessons do
    get 'accept' => :accept
    get 'refuse' => :refuse
    get 'cancel' => :cancel
    get 'pay_teacher'=>:pay_teacher
    get 'dispute'=>:dispute
    
    resources :payments do
      resources :pay_postpayments
    end
    post "create_postpayment" => "payments#create_postpayment"
    get "edit_postpayment/:payment_id" => "payments#edit_postpayment", as: 'edit_postpayment'
    post "edit_postpayment/:payment_id" => "payments#send_edit_postpayment", as: 'send_edit_postpayment'

    post "payerfacture/:payment_id" => "payments#payerfacture", as: 'payerfacture'
  end
  match '/cours' =>'lessons#index', :as => 'cours', via: :get
  match '/cours/recus'=>'lessons#received', :as => 'cours_recus', via: :get
  match '/cours/donnes'=>'lessons#given', :as => 'cours_donnes', via: :get
  match '/cours/historique'=>'lessons#history', :as => 'cours_historique', via: :get
  match '/cours/pending'=>'lessons#pending', :as => 'cours_pending', via: :get

  resources :messages, only: [:new, :create, ]
  post "/typing" => "messages#typing"
  post "/seen" => "messages#seen"
  get "/level_choice" => "adverts#choice"
  get "/topic_choice" => "adverts#choice_group"
  post "conversation/show_min" => "conversations#find"
  get "conversation/show_min/:conversation_id" => "conversations#show_min"

  # BBB rooms et recordings
  bigbluebutton_routes :default, :only => 'rooms', :controllers => {:rooms => 'bbb_rooms'}
  resource :bbb_rooms do
    get "/room_invite/:user_id" => "bbb_rooms#room_invite", as: 'room_invite'
    get "/end_room/:room_id" => "bbb_rooms#end_room", as: 'end_room'
  end
  bigbluebutton_routes :default, :only => 'recordings', :controllers => {:rooms => 'bbb_recordings'}

  mount Resque::Server, :at => "/resque"

  #root to: 'pages#index'
end

app/views/bigbluebutton/rooms/_form.html.haml
- if @room.new_record?
  - url = bigbluebutton_rooms_path
- else
  - url = bigbluebutton_room_path(@room)
= form_for setup_bigbluebutton_room(@room), :url => url do |f|
  - if @room.errors.any?
    #error_explanation
      %h2
        = pluralize(@room.errors.count, "error")
        \:
      %ul
        - @room.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :id
    %br/
    = @room.id
  .field
    = f.label :server_id
    %br/
    = f.text_field :server_id
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :meetingid
    %br/
    = f.text_field :meetingid
  .field
    = f.label :private
    %br/
    = f.check_box :private
  .field
    = f.label :attendee_key
    %br/
    = f.text_field :attendee_key
  .field
    = f.label :moderator_key
    %br/
    = f.text_field :moderator_key
  .field
    = f.label :welcome_msg
    %br/
    = f.text_field :welcome_msg
  .field
    = f.label :logout_url
    %br/
    = f.text_field :logout_url
  .field
    = f.label :dial_number
    %br/
    = f.text_field :dial_number
  .field
    = f.label :voice_bridge
    %br/
    = f.text_field :voice_bridge
  .field
    = f.label :max_participants
    %br/
    = f.text_field :max_participants
  .field
    = f.label :external
    %br/
    = f.check_box :external
  .field
    = f.label :param
    %br/
    = f.text_field :param
  .field
    = f.label :record_meeting
    %br/
    = f.check_box :record_meeting
  .field
    = f.label :duration
    %br/
    = f.text_field :duration
  .field
    = f.label :moderator_only_message
    %br/
    = f.text_field :moderator_only_message
    %br/
  .field
    = f.label :auto_start_recording
    %br/
    = f.check_box :auto_start_recording
    %br/
  .field
    = f.label :allow_start_stop_recording
    %br/
    = f.check_box :allow_start_stop_recording
    %br/
  .field
    %b Metadata
    (by default we have 10 metadata in this view, but it's not limited to it)
    %br/
    = f.fields_for :metadata do |metadata_form|
      = metadata_form.label :name
      = metadata_form.text_field :name
      = metadata_form.label :content
      = metadata_form.text_field :content
      = metadata_form.check_box :_destroy
      = metadata_form.label :_destroy, "Remove Metadata"
      %br/
  .actions
    = f.submit

app/views/bigbluebutton/rooms/_rooms.html.haml
#bbbrails_rooms_links
  = link_to('View server list', bigbluebutton_servers_path)
  %br/
  = link_to('View recording list', bigbluebutton_recordings_path)
  %br/
  = link_to('New room', new_bigbluebutton_room_path)
%ul#bbbrails_list
  - @rooms.each do |room|
    %li
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:id)
        = room.id
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:server_id)
        = room.server_id
        = link_to('(view server)', bigbluebutton_server_path(room.server)) unless room.server.nil?
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:name)
        = room.name
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:meetingid)
        = room.meetingid
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:private)
        = room.private
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:attendee_key)
        = room.attendee_key
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:moderator_key)
        = room.moderator_key
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:welcome_msg)
        = room.welcome_msg
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:logout_url)
        = room.logout_url
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:dial_number)
        = room.dial_number
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:voice_bridge)
        = room.voice_bridge
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:max_participants)
        = room.max_participants
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:external)
        = room.external
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:param)
        = room.param
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:record_meeting)
        = room.record_meeting
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:duration)
        = room.duration
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:moderator_only_message)
        = room.moderator_only_message
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:auto_start_recording)
        = room.auto_start_recording
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:allow_start_stop_recording)
        = room.allow_start_stop_recording
      .field
        %label= BigbluebuttonRoom.human_attribute_name(:metadata)
        %div
          - room.metadata.each do |metadata|
            = metadata.attributes.except("id", "owner_id", "owner_type", "updated_at", "created_at")
            ,
      .field
        %label Access
        = link_to 'Show', bigbluebutton_room_path(room)
        |
        \#{link_to 'Join', join_bigbluebutton_room_path(room)} |
        \#{link_to 'Invite', invite_bigbluebutton_room_path(room)} |
        \#{link_to 'Mobile Join', join_mobile_bigbluebutton_room_path(room)} |
        \#{link_to 'Edit', edit_bigbluebutton_room_path(room)} |
        \#{link_to 'End', end_bigbluebutton_room_path(room), :confirm => 'Are you sure?'} |
        \#{link_to 'Destroy', bigbluebutton_room_path(room), :confirm => 'Are you sure?', :method => :delete}
      .field
        %label Recordings
        = link_to 'View recordings', recordings_bigbluebutton_room_path(room)
        |
        \#{link_to 'Fetch recordings', fetch_recordings_bigbluebutton_room_path(room), :confirm => 'Are you sure?', :method => :post}

app/views/bigbluebutton/rooms/edit.html.haml
%h1
  Edit #{BigbluebuttonRoom.model_name.human}:
= render 'form'
= link_to 'Show', bigbluebutton_room_path(@room)
|
= link_to 'Back', bigbluebutton_rooms_path

app/views/bigbluebutton/rooms/external.html.haml
%h1
  Join the meeting #{@room.name}
#error_explanation= flash[:error]
%p
  This meeting was created from another application.
  %br>/
  You must provide a name and a password to join:
= form_tag external_bigbluebutton_rooms_path do
  = hidden_field_tag "server_id", params[:server_id]
  = hidden_field_tag "meeting", params[:meeting]
  .field
    %label{:for => "user_name"} Name:
    %br/
    - if bigbluebutton_user.nil?
      = text_field_tag "user[name]", ""
    - else
      = text_field_tag "user[name]", bigbluebutton_user.name
  .field
    %label{:for => "user_password"} Password:
    %br/
    = password_field_tag "user[password]", ""
  = submit_tag "Submit"

app/views/bigbluebutton/rooms/index.html.haml
%h1 Listing rooms:
= render 'rooms'

app/views/bigbluebutton/rooms/invite.html.haml
:javascript
  function ajax_request() {
    $.ajax({
      url: "#{running_bigbluebutton_room_url(@room, :format => 'json')}",
      dataType: 'json',
      error: function(xhr_data) {
        $("#meeting_status").html("<request error>.");
        setTimeout(function() { ajax_request(); }, 10000);
      },
      success: function(xhr_data) {
        if (xhr_data.running == 'false') {
          $("#meeting_status").html("not running.");
        } else {
          $("#meeting_status").html("running!");
        }
        setTimeout(function() { ajax_request(); }, 10000);
      },
      contentType: 'application/json'
    });
  }
  
  $(document).ready(function(){
    ajax_request();
  });
%h1
  Invite to the meeting #{@room.name}
/ A helper to show errors, add it to the views were you need it
/ <haml_loud> bbb_rails_error_explanation </haml_loud>
%p
  Meeting status:
  %span#meeting_status -
  (
  %a{:href => "javascript:ajax_request();"}> refresh
  )
.bbbrails_invite_device_type
  - if params[:mobile]
    In this page you can join the conference from a
    = succeed "." do
      %b mobile device
    = link_to "click here", invite_bigbluebutton_room_path(@room)
    \.
  - else
    In this page you can join the conference from a
    = succeed "." do
      %b desktop
    = link_to "click here", invite_bigbluebutton_room_path(@room, :mobile => true)
    \.
- saved_room = BbbRoom.where(:param => @room)
- lesson = saved_room.lesson
%p
  LESSSON = #{lesson}
%h1 LEEEEEEEES
%p
  = @room.name
  requires a name and/or key to join:
= form_tag join_bigbluebutton_room_path(@room, :mobile => params[:mobile]) do
  .field
    %label{:for => "user_name"} Name:
    %br/
    - if bigbluebutton_user.nil?
      = text_field_tag "user[name]", ""
    - else
      = text_field_tag "user[name]", bigbluebutton_user.name, :readonly => true
  .field
    %label{:for => "user_key"} Key:
    %br/
    - if @user_role == :attendee
      = password_field_tag "user[key]", @room.attendee_key, :readonly => true
    - elsif @user_role == :moderator
      = password_field_tag "user[key]", @room.moderator_key, :readonly => true
    - else
      = password_field_tag "user[key]", ""
  = submit_tag "Submit"

app/views/bigbluebutton/rooms/join.html.haml
:javascript
  function ajax_request() {
    $.ajax({
      url: "#{running_bigbluebutton_room_url(@room, :format => 'json')}",
      dataType: 'json',
      error: function(xhr_data) {
        //
      },
      success: function(xhr_data) {
        if (xhr_data.running == 'true') {
          window.location.reload();
        }
        setTimeout(function() { ajax_request(); }, 3000);
      },
      contentType: 'application/json'
    });
  }
  
  $(document).ready(function(){
    ajax_request();
  });
%h1
  Meeting #{@room.name}
%p The meeting has not started yet, you must wait for the moderator to join.
%p Your browser will automatically refresh and join the meeting when it starts.

app/views/bigbluebutton/rooms/join_mobile.html.haml
:javascript
  $(document).ready(function(){
    window.location.href = "#{@join_mobile}";
  });
%h1
  Mobile access to #{@room.name}
%div{:style => "text-align:center; width:250px;"}
  %span You are being redirected to the conference in your mobile device.
  %br/
  %div
    %span If you are not redirected, please make sure you have the mobile client installed:
    %div
      = link_to(mobile_google_play_link, :class => "mobile-download-image") do
        = image_tag mobile_google_play_image, :alt => "Download the Android client", :title => "Download the Android client"
    %div
      = link_to(mobile_apple_store_link, :class => "mobile-download-image") do
        = image_tag mobile_apple_store_image, :alt => "Download the iOS client", :title => "Download the iOS client"
  %br/
  %div
    = link_to "You have the application but still hasn't been redirected? Click here to try again.", @join_mobile
  %br/
  %div
    = link_to "If you are not on a mobile client, click here to log in using the default desktop client.", @join_desktop

app/views/bigbluebutton/rooms/new.html.haml
%h1
  New #{BigbluebuttonRoom.model_name.human}:
= render 'form'
= link_to 'Back', bigbluebutton_rooms_path

app/views/bigbluebutton/rooms/recordings.html.haml
%h1
  Listing recordings for the room "#{@room.name}":
= render 'bigbluebutton/recordings/recordings'

app/views/bigbluebutton/rooms/show.html.haml
%h1
  = BigbluebuttonRoom.model_name.human
  \:
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:id)
    \:
  = @room.id
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:server_id)
    \:
  = @room.server_id
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:name)
    \:
  = @room.name
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:meetingid)
    \:
  = @room.meetingid
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:private)
    \:
  = @room.private
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:attendee_key)
    \:
  = @room.attendee_key
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:moderator_key)
    \:
  = @room.moderator_key
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:welcome_msg)
    \:
  = @room.welcome_msg
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:logout_url)
    \:
  = @room.logout_url
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:dial_number)
    \:
  = @room.dial_number
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:voice_bridge)
    \:
  = @room.voice_bridge
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:max_participants)
    \:
  = @room.max_participants
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:external)
    \:
  = @room.external
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:param)
    \:
  = @room.param
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:record_meeting)
    \:
  = @room.record_meeting
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:duration)
    \:
  = @room.duration
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:moderator_only_message)
    \:
  = @room.moderator_only_message
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:auto_start_recording)
    \:
  = @room.auto_start_recording
%p
  %b
    = BigbluebuttonRoom.human_attribute_name(:allow_start_stop_recording)
    \:
  = @room.allow_start_stop_recording
%p
  %b= BigbluebuttonRoom.human_attribute_name(:metadata)
  - @room.metadata.each do |metadata|
    = metadata.attributes.except("id", "owner_id", "owner_type", "updated_at", "created_at")
    ,
= link_to 'Edit', edit_bigbluebutton_room_path(@room)
|
= link_to 'Back', bigbluebutton_rooms_path
%br/
%p
  %span Access:
  = link_to 'Show', bigbluebutton_room_path(@room)
  |
  \#{link_to 'Join', join_bigbluebutton_room_path(@room)} |
  \#{link_to 'Invite', invite_bigbluebutton_room_path(@room)} |
  \#{link_to 'Mobile Join', join_mobile_bigbluebutton_room_path(@room)} |
  \#{link_to 'End', end_bigbluebutton_room_path(@room), :confirm => 'Are you sure?'} |
  \#{link_to 'Destroy', bigbluebutton_room_path(@room), :confirm => 'Are you sure?', :method => :delete}
%p
  %span Recordings:
  = link_to 'View recordings', recordings_bigbluebutton_room_path(@room)
  |
  \#{link_to 'Fetch recordings', fetch_recordings_bigbluebutton_room_path(@room), :confirm => 'Are you sure?', :method => :post}