config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :students
    resources :teachers
    resources :pictures
    resources :galleries
    resources :postulations
    resources :comments
    resources :postuling_teachers
    resources :lessons
    resources :topics
    resources :topic_groups
    resources :level
    resources :advert_prices
    resources :adverts
    resources :payments

    

    get "/user_conversation/:id", to: "users#show_conversation", as: 'show_conversation'
    
   
    # Gestion des serveurs BBB depuis l'admin
    resources :bigbluebutton_servers
    resources :bigbluebutton_recordings
    resources :bbb_rooms

    root to: "users#index"
  end
  resources "contact", only: [:new, :create]
    


  scope '/user/mangopay', controller: :payments do
  end

  scope '/user/mangopay', controller: :wallets do
    get "edit_wallet" => :edit_mangopay_wallet
    put "edit_wallet" => :update_mangopay_wallet
    get "index_wallet" => :index_mangopay_wallet
    get "direct_debit" => :direct_debit_mangopay_wallet
    put "direct_debit" => :load_wallet
    get "transactions" => :transactions_mangopay_wallet
    get "card_info" => :card_info
    put "send_card_info" => :send_card_info
    get 'bank_accounts' => :bank_accounts
    put 'update_bank_accounts' => :update_bank_accounts
    get 'payout' => :payout
    put 'make_payout' => :make_payout
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations=> "registrations" }

  resources :users, only: [:update] do
    patch 'crop' => 'users#crop'
    post 'crop' => 'users#crop'
  end

  get 'dashboard' => 'dashboards#index', :as => 'dashboard'
  get 'featured_reviews' => 'reviews#featured_reviews'

  resources :users, :only => [:show] do
    resources :require_lesson
    put '/lesson_requests/payment' => 'lesson_requests/payment'
    resources :lesson_requests, only: [:new, :create] do
      get 'topics/:topic_group_id', action: :topics, on: :collection
      get 'levels/:topic_id', action: :levels, on: :collection
      post :calculate, on: :collection
      get :credit_card_process, on: :collection
      get :bancontact_process, on: :collection
      post :create_account, on: :collection
    end
    resources :reviews, only: [:index, :create, :new]
  end
  get '/both_users_online' => 'users#both_users_online', :as => 'both_users_online'
  authenticated :user do
    root 'dashboards#index'
  end
  resources :topics do
    get :autocomplete_topic_title, :on => :collection
  end
  match "/profs/" => "users#profs_by_topic", as: :profs, via: :post
  match "/profs/:topic" => "users#index", :as => :profs_by_topic, :via => [:get]
  get "/profs" => "users#index"

  unauthenticated :user do
    devise_scope :user do
      get "/" => "pages#index"
    end
  end
  resources :galleries, only: [:update, :edit, :show]
  resources :pictures, only: [:new, :destroy, :show]
  resources :degrees
  resources :notifications
  get "/notifications/unread/" => "notifications#number_of_unread"

  resources :adverts do
    resources :advert_prices
  end

  get '/adverts_user/:user_id', to: 'adverts#get_all_adverts', as: 'get_all_adverts'

  get "/pages/*page" => "pages#show"
  resources :pages do

  end
  get '/become_teacher/accueil' => "pages#devenir-prof"
  get '/index' => "pages#index"
  resources :become_teacher
  resources :conversations, only: [:index, :show, :delete] do
    member do
      post :reply
      post :mark_as_read
      post :trash
      post :mark_as_unread
      post :untrash
    end
  end
  match 'mailbox' => 'conversations#index', :as => 'messagerie', via: :get
  match 'mailbox/:mailbox' => 'conversations#index', :as => 'mailbox', via: :get
  post 'mailbox/search' => 'conversations#search'

  #Permet affichage facture
  get "/payments/index" => "payments#index"
  
  #post "lessons/:teacher_id/require_lesson", to: "lessons#require_lesson", as: 'require_lesson'
  resources :lessons do
    get 'accept' => :accept
    get 'refuse' => :refuse
    get 'cancel' => :cancel
    get 'pay_teacher'=>:pay_teacher
    get 'dispute'=>:dispute
    
    resources :payments do
      resources :pay_postpayments
    end
    post "create_postpayment" => "payments#create_postpayment"
    get "edit_postpayment/:payment_id" => "payments#edit_postpayment", as: 'edit_postpayment'
    post "edit_postpayment/:payment_id" => "payments#send_edit_postpayment", as: 'send_edit_postpayment'

    post "payerfacture/:payment_id" => "payments#payerfacture", as: 'payerfacture'
  end
  match '/cours' =>'lessons#index', :as => 'cours', via: :get
  match '/cours/recus'=>'lessons#received', :as => 'cours_recus', via: :get
  match '/cours/donnes'=>'lessons#given', :as => 'cours_donnes', via: :get
  match '/cours/historique'=>'lessons#history', :as => 'cours_historique', via: :get
  match '/cours/pending'=>'lessons#pending', :as => 'cours_pending', via: :get

  resources :messages, only: [:new, :create, ]
  post "/typing" => "messages#typing"
  post "/seen" => "messages#seen"
  get "/level_choice" => "adverts#choice"
  get "/topic_choice" => "adverts#choice_group"
  post "conversation/show_min" => "conversations#find"
  get "conversation/show_min/:conversation_id" => "conversations#show_min"

  # BBB rooms et recordings
  bigbluebutton_routes :default, :only => 'rooms', :controllers => {:rooms => 'bbb_rooms'}
  resource :bbb_rooms do
    get "/room_invite/:user_id" => "bbb_rooms#room_invite", as: 'room_invite'
    get "/end_room/:room_id" => "bbb_rooms#end_room", as: 'end_room'
  end
  bigbluebutton_routes :default, :only => 'recordings', :controllers => {:rooms => 'bbb_recordings'}

  mount Resque::Server, :at => "/resque"

  #root to: 'pages#index'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = current_user
    @upcoming_lessons = Lesson.where(:status => 2).where('time_start > ?', DateTime.now).where("student_id =#{@user.id}  OR teacher_id = #{@user.id}")
    @past_lessons = Lesson.involving(@user).passed.limit(3).order(time_start: :desc)

    unless @past_lessons.empty?
      @past_lessons.each do |lesson|
        if lesson.student == current_user
          @book_again_lesson = lesson
        end
      end
      while @past_lessons.length < 3
        @past_lessons.append(nil)
      end
    end

    unless(@user.mango_id.nil?)
      @wallets = {normal: @user.wallets.first, bonus: @user.wallets.second, transfer: @user.wallets.third}
    end

    @to_do_list =@user.todo_lessons.sort_by &:created_at

    @featured_topics = TopicGroup.where(featured: true) + Topic.where(featured: true)
    @featured_teachers = Teacher.all.order(score: :desc).limit(5)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/todo_list/_todo_answer.html.haml
.todo
  .row
    .col-sm-2.col-hidden-xs
      = image_tag lesson.other(current_user).avatar(:medium), class: 'img todo_review_img'
    .col-sm-7.col-xs-9.todo_answer
      %h3.todo_title
        #{lesson.other(current_user).firstname} vous a fait une demande de cours!
      .todo-details
        #{distance_of_time_in_words(lesson.time_start, lesson.time_end)} de
        #{link_to lesson.topic.title, profs_by_topic_path(lesson.topic.title), class: 'text-purple'} avec
        #{link_to lesson.teacher.name, user_path(lesson.teacher), class: 'text-purple'}
        %br
        %span{data: {toggle: 'tooltip', placement: 'bottom'}, title: "#{lesson.time_start.strftime('Timezone: %Z')}"}
          #{lesson.time_start.strftime('Le %d/%m/%Y à %R')}
    .col-xs-3.todo_answer.text-center.todo_action
      = link_to 'Accepter', lesson_accept_path(lesson), class: 'btn btn-qw btn-green btn-sm'
      = button_to 'Modifier', '#', class: 'btn btn-qw btn-orange btn-sm'
      = link_to 'Décliner', lesson_refuse_path(lesson), class: 'text-grey'

app/views/dashboards/todo_list/_todo_payment.html.haml
.todo
  .row
    .col-sm-2.col-hidden-xs
      .text-center.todo_payment_img
        #{lesson.id}
        = image_tag('todo_payment.png')
    .col-sm-7.col-xs-9.todo_payment
      %h3.todo_title
        Comment s'est passé votre cours ?
      .todo-details
        #{distance_of_time_in_words(lesson.time_start, lesson.time_end)} de
        #{link_to lesson.topic.title, profs_by_topic_path(lesson.topic.title), class: 'text-purple'} avec
        #{link_to lesson.teacher.name, user_path(lesson.teacher), class: 'text-purple'}
        %br
        %span{data: {toggle: 'tooltip', placement: 'bottom'}, title: "#{lesson.time_start.strftime('Timezone: %Z')}"}
          #{lesson.time_start.strftime('Le %d/%m/%Y à %R')}
    .col-xs-3.todo_payment.text-center.todo_action
      = button_to 'Tout s\'est bien passé', lesson_pay_teacher_path(lesson), class: 'btn btn-qw btn-green btn-sm'
      = link_to 'Signaler un problème', lesson_dispute_path(lesson), class: 'text-grey'

app/views/dashboards/todo_list/_todo_review.html.haml
.todo
  .row
    .col-sm-2.col-hidden-xs
      = image_tag (lesson.teacher.avatar(:medium)), class: 'img todo_review_img'
    .col-sm-7.col-xs-9.todo_review
      %h3.todo_title
        Recommanderiez-vous #{lesson.teacher.firstname} ?
      %div
        = render partial: 'shared/star_rating', locals:{note: lesson.teacher.avg_reviews}
    .col-xs-3.todo_review.text-center.todo_action
      = button_to 'Laisser un avis', '#', class: 'btn btn-qw btn-green btn-sm'
      = link_to 'Pas maintenant', '#', class: 'text-grey'