config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :students
    resources :teachers
    resources :pictures
    resources :galleries
    resources :postulations
    resources :comments
    resources :postuling_teachers
    resources :lessons
    resources :topics
    resources :topic_groups
    resources :level
    resources :advert_prices
    resources :adverts
    resources :payments

    

    get "/user_conversation/:id", to: "users#show_conversation", as: 'show_conversation'
    
   
    # Gestion des serveurs BBB depuis l'admin
    resources :bigbluebutton_servers
    resources :bigbluebutton_recordings
    resources :bbb_rooms

    root to: "users#index"
  end
  resources "contact", only: [:new, :create]
    


  scope '/user/mangopay', controller: :payments do
  end

  scope '/user/mangopay', controller: :wallets do
    get "edit_wallet" => :edit_mangopay_wallet
    put "edit_wallet" => :update_mangopay_wallet
    get "index_wallet" => :index_mangopay_wallet
    get "direct_debit" => :direct_debit_mangopay_wallet
    put "direct_debit" => :load_wallet
    get "transactions" => :transactions_mangopay_wallet
    get "card_info" => :card_info
    put "send_card_info" => :send_card_info
    get 'bank_accounts' => :bank_accounts
    put 'update_bank_accounts' => :update_bank_accounts
    get 'payout' => :payout
    put 'make_payout' => :make_payout
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations=> "registrations" }

  resources :users, only: [:update] do
    patch 'crop' => 'users#crop'
    post 'crop' => 'users#crop'
  end

  get 'dashboard' => 'dashboards#index', :as => 'dashboard'
  get 'featured_reviews' => 'reviews#featured_reviews'

  resources :users, :only => [:show] do
    resources :require_lesson
    put '/lesson_requests/payment' => 'lesson_requests/payment'
    resources :lesson_requests, only: [:new, :create] do
      get 'topics/:topic_group_id', action: :topics, on: :collection
      get 'levels/:topic_id', action: :levels, on: :collection
      post :calculate, on: :collection
      get :credit_card_process, on: :collection
      get :bancontact_process, on: :collection
      post :create_account, on: :collection
    end
    resources :reviews, only: [:index, :create, :new]
  end
  get '/both_users_online' => 'users#both_users_online', :as => 'both_users_online'
  authenticated :user do
    root 'dashboards#index'
  end
  resources :topics do
    get :autocomplete_topic_title, :on => :collection
  end
  match "/profs/" => "users#profs_by_topic", as: :profs, via: :post
  match "/profs/:topic" => "users#index", :as => :profs_by_topic, :via => [:get]
  get "/profs" => "users#index"

  unauthenticated :user do
    devise_scope :user do
      get "/" => "pages#index"
    end
  end
  resources :galleries, only: [:update, :edit, :show]
  resources :pictures, only: [:new, :destroy, :show]
  resources :degrees
  resources :notifications
  get "/notifications/unread/" => "notifications#number_of_unread"

  resources :adverts do
    resources :advert_prices
  end

  get '/adverts_user/:user_id', to: 'adverts#get_all_adverts', as: 'get_all_adverts'

  get "/pages/*page" => "pages#show"
  resources :pages do

  end
  get '/become_teacher/accueil' => "pages#devenir-prof"
  get '/index' => "pages#index"
  resources :become_teacher
  resources :conversations, only: [:index, :show, :delete] do
    member do
      post :reply
      post :mark_as_read
      post :trash
      post :mark_as_unread
      post :untrash
    end
  end
  match 'mailbox' => 'conversations#index', :as => 'messagerie', via: :get
  match 'mailbox/:mailbox' => 'conversations#index', :as => 'mailbox', via: :get
  post 'mailbox/search' => 'conversations#search'

  #Permet affichage facture
  get "/payments/index" => "payments#index"
  
  #post "lessons/:teacher_id/require_lesson", to: "lessons#require_lesson", as: 'require_lesson'
  resources :lessons do
    get 'accept' => :accept
    get 'refuse' => :refuse
    get 'cancel' => :cancel
    get 'pay_teacher'=>:pay_teacher
    get 'dispute'=>:dispute
    
    resources :payments do
      resources :pay_postpayments
    end
    post "create_postpayment" => "payments#create_postpayment"
    get "edit_postpayment/:payment_id" => "payments#edit_postpayment", as: 'edit_postpayment'
    post "edit_postpayment/:payment_id" => "payments#send_edit_postpayment", as: 'send_edit_postpayment'

    post "payerfacture/:payment_id" => "payments#payerfacture", as: 'payerfacture'
  end
  match '/cours' =>'lessons#index', :as => 'cours', via: :get
  match '/cours/recus'=>'lessons#received', :as => 'cours_recus', via: :get
  match '/cours/donnes'=>'lessons#given', :as => 'cours_donnes', via: :get
  match '/cours/historique'=>'lessons#history', :as => 'cours_historique', via: :get
  match '/cours/pending'=>'lessons#pending', :as => 'cours_pending', via: :get

  resources :messages, only: [:new, :create, ]
  post "/typing" => "messages#typing"
  post "/seen" => "messages#seen"
  get "/level_choice" => "adverts#choice"
  get "/topic_choice" => "adverts#choice_group"
  post "conversation/show_min" => "conversations#find"
  get "conversation/show_min/:conversation_id" => "conversations#show_min"

  # BBB rooms et recordings
  bigbluebutton_routes :default, :only => 'rooms', :controllers => {:rooms => 'bbb_rooms'}
  resource :bbb_rooms do
    get "/room_invite/:user_id" => "bbb_rooms#room_invite", as: 'room_invite'
    get "/end_room/:room_id" => "bbb_rooms#end_room", as: 'end_room'
  end
  bigbluebutton_routes :default, :only => 'recordings', :controllers => {:rooms => 'bbb_recordings'}

  mount Resque::Server, :at => "/resque"

  #root to: 'pages#index'
end

app/controllers/lesson_requests_controller.rb
class LessonRequestsController < ApplicationController
  before_filter :authenticate_user!
  before_action :find_users
  before_action :check_mangopay_account, only: :payment
  before_action :set_lesson, expect: [:topics, :levels, :calculate]
  before_filter :user_time_zone, :if => :current_user

  after_filter { flash.discard if request.xhr? }

  def new
    @free_lessons = @user.free_lessons_with(@teacher)
    @lesson_request = @lesson.present? ? CreateLessonRequest.from_lesson(@lesson) : CreateLessonRequest.new
  end

  def create
    Lesson.drafts(current_user).destroy_all
    @free_lessons = @user.free_lessons_with(@teacher)
    saving = CreateLessonRequest.run(request_params)
    if saving.valid?
      @lesson = saving.result
      if @lesson.free_lesson
        @lesson.save
        render 'finish'
      elsif check_mangopay_account
        creation = Mango::CreateCardRegistration.run(user: current_user)
        if !creation.valid?
          render 'errors', :layout=>false, locals: {object: creation}
        else
          @card_registration = creation.result
          render 'payment_method'
        end
      end
    else
      render 'errors', :layout=>false, locals: {object: saving}
    end
  end

  def payment
    render 'new' and return if @lesson.nil?

    case params[:mode]

      when 'transfert'
        paying = PayLessonByTransfert.run(user: current_user, lesson: @lesson)
        if paying.valid?
          render 'finish', :layout => false
        else
          @card_registration = Mango::CreateCardRegistration.run(user: current_user).result
          render 'errors', :layout=>false, locals: {object: paying}
        end

      when 'bancontact'
        return_url = bancontact_process_user_lesson_requests_url(@teacher)
        payin = Mango::PayinBancontact.run(user: current_user, amount: @lesson.price,
          return_url: return_url, wallet: 'transaction')
        if payin.valid?
          render js: "window.location = '#{payin.result.redirect_url}'" and return
        else
          render 'errors', :layout=>false, locals: {object: payin}
        end

      when 'cd'
        return_url = credit_card_process_user_lesson_requests_url(@teacher)
        payin = Mango::PayinCreditCard.run({user: current_user, amount: @lesson.price,
          card_id: params[:card_id], return_url: return_url, wallet: 'transaction'})

        if payin.valid?
          result = payin.result
          if result.secure_mode == 'FORCE' and result.secure_mode_redirect_url.present?
            render js: "window.location = '#{result.secure_mode_redirect_url}'" and return
          else
            paying = PayLessonWithCard.run(user: current_user, lesson: @lesson, transaction_id: result.id)
            if !paying.valid?
              render 'errors', :layout=>false, locals: {object: paying}
            else
              render 'finish', :layout => false
            end
          end
        else
          render 'errors', :layout=>false, locals: {object: payin}
        end

    end
  end

  def credit_card_process
    processing = PayLessonWithCard.run(user: current_user, lesson: @lesson, transaction_id: params[:transactionId])
    if processing.valid?
      redirect_to lessons_path, notice: t('notice.booking_success')
    else
      redirect_to user_path(@lesson.teacher), notice: t('notice.booking_error')
    end
  end

  def bancontact_process
    processing = PayLessonByBancontact.run(user: current_user, lesson: @lesson, transaction_id: params[:transactionId])
    if processing.valid?
      redirect_to lessons_path, notice: t('notice.booking_success')
    else
      redirect_to user_path(@lesson.teacher), notice: t('notice.booking_error')
    end
  end

  def topics
    @topics = @teacher.adverts.includes(:topic).where(topics: params.slice(:topic_group_id)).uniq
      .pluck_to_hash('topics.id as id', 'topics.title as title')
    render json: @topics
  end

  def levels
    @levels = @teacher.adverts.includes(advert_prices: :level).where(topic_id: params[:topic_id]).uniq
      .pluck_to_hash('levels.id as id', 'levels.fr as title')
    render json: @levels
  end

  def calculate
    @calc = CalculateLessonPrice.run(calculating_params)
    if @calc.valid?
      render json: {price: @calc.result}
    else
      render json: {error: @calc.errors.full_messages.first}
    end
  end

  def create_account
    saving = Mango::SaveAccount.run( params.fetch(:account).permit!.merge(user: current_user) )
    if saving.valid?
      @card_registration = Mango::CreateCardRegistration.run(user: current_user).result
      render 'payment_method'
    else
      render 'errors', :layout=>false, locals: {object: saving}
    end
  end

  private

  def find_users
    @user = current_user
    @teacher = Teacher.find(params[:user_id])
  end

  def set_lesson
    @lesson = Lesson.drafts(current_user).first.try(:restore)
  end

  def lesson_params
    params.require(:lesson).permit(:student_id, :date, :teacher_id, :price, :level_id, :topic_id, :topic_group_id, :time_start, :time_end, :free_lesson).merge(:student_id => current_user.id)
  end

  def request_params
    params.require(:request).permit(:student_id, :level_id, :topic_id, :time_start, :hours, :minutes, :free_lesson).merge({
      :student_id => current_user.id,
      :teacher_id => @teacher.id
    })
  end

  def calculating_params
    params.slice(:hours, :minutes, :topic_id, :level_id).merge(teacher_id: @teacher.id)
  end

  def check_mangopay_account
    return true if current_user.mango_id.present?
    @account = Mango::SaveAccount.new(user: current_user, first_name: current_user.firstname, last_name: current_user.lastname)
    render 'mango_account', :layout=>false and return false
  end


end

app/helpers/lesson_requests_helper.rb
module LessonRequestsHelper
end

app/views/lesson_requests/_finish.html.haml
%h2 Merci! Votre demande a bien été envoyée au professeur.
=@lesson.inspect

app/views/lesson_requests/_form.html.haml
= form_for @lesson_request, as: :request, url: user_lesson_requests_path(@teacher), method: :post, remote: true, html: {class: 'request-lession-form'} do |f|
  = hidden_field_tag 'lesson[teacher_id]', @teacher.id
  = render 'shared/errors', object: f.object
  .form-group
    - if @teacher.first_lesson_free == true && @free_lessons.empty?
      = f.check_box :free_lesson, class: 'firstLessonFree', id: 'free_lesson'
      = f.label :free_lesson, "Cours d'essai gratuit 30mn", for: 'free_lesson'
      %br

  .form-group
    = f.label :time_start
    #datetimepicker.input-group.date
      = f.text_field :time_start, class: 'form-control', :required => true
      %span.input-group-addon
        %span.glyphicon.glyphicon-calendar

  .form-group
    = label_tag :time, 'Durée', class: 'control-label'
    .row
      .col-xs-3= select_hour f.object.hours, {prefix: :request, field_name: :hours, start_hour: 0, :end_hour => 5}, {class: 'form-control hours-select', required: true}
      .col-xs-3= select_minute f.object.minutes, {prefix: :request, field_name: :minutes, minute_step: 15}, {class: 'form-control minutes-select', required: true}

  .form-group
    = f.label :topic_group_id
    - options = @teacher.adverts.map(&:topic).map(&:topic_group).uniq.compact.map{|tg| [tg.title, tg.id]}
    = f.select :topic_group_id, options, {prompt: '-- sélecitonnez un niveau --'}, {class: 'form-control topic-group-select'}

  .form-group
    = f.label :topic_id
    - if f.object.topic_group_id.present?
      - options = @teacher.adverts.map(&:topic).select{|t| t.topic_group_id == f.object.topic_group_id}.uniq.compact.map{|tg| [tg.title, tg.id]}
    - else
      - options = []
    = f.select :topic_id, options, {prompt: '-- sélecitonnez un niveau --'}, {class: 'form-control topic-select'}

  .form-group
    = f.label :level_id
    - if f.object.topic_id.present?
      - options = @teacher.adverts.includes(advert_prices: :level).where(topic_id: f.object.topic_id).uniq.pluck('levels.fr', 'levels.id')
    - else
      - options = []
    = f.select :level_id, options, {prompt: '-- sélecitonnez un niveau --'}, {class: 'form-control level-select'}

  .form-actions
    %h4
      %span#price_shown= f.object.try(:calculate_price) || 0
      €
    = submit_tag :enregistrer, :class => 'btn btn-primary btn-mini'

app/views/lesson_requests/_mango_account.html.haml
%h3 Informations de payement
= form_for @account, as: :account, url:  create_account_user_lesson_requests_path(@teacher), remote: true do |f|
  = render 'mangopay/account_fields', f: f
  .field
    = submit_tag 'terminer', :class => 'btn btn-primary btn-mini'
    %br/

app/views/lesson_requests/_new.html.haml
= form_tag user_request_lesson_index_path(@teacher), method: :post, remote: true do |f|
  - unless @lesson.errors.empty?
    .alert.alert-danger
      - @lesson.errors.full_messages.each do |message|
        %li= message
  = hidden_field_tag 'lesson[teacher_id]', @teacher.id
  #price
    .form-group
      - if @teacher.first_lesson_free == true && @free_lessons.empty?
        %input{:name => "firstLessonFree", :type => "checkbox", :class => "firstLessonFree", :checked=> @lesson.free_lesson}
        Cours d'essai gratuit 30mn
        %br
  .form-group
    = label_tag :time_start
    #datetimepicker2.input-group.date
      = text_field_tag 'lesson[time_start]', nil, class: 'form-control', :required => true
      %span.input-group-addon
        %span.glyphicon.glyphicon-calendar
  .form-group
    = hidden_field_tag 'lesson[time_end]'
  .form-group
    = label_tag 'Durée'
    = select_hour @hours, :field_name => 'lesson[hour]', :start_hour => 0, :end_hour => 5, class: 'form-control', :required => true
    = select_minute @minutes, :field_name => 'lesson[minute]', :minute_step => 15, class: 'form-control', :required => true
  #choices_lessons_topic_group
  #choices_lessons_topic
  #choices_lessons_level
  .form-actions
    %h4
      %span#price_shown 0
      €
    = submit_tag :enregistrer, :class => 'btn btn-primary btn-mini'

app/views/lesson_requests/_payment.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    = value

app/views/lesson_requests/_payment_method.html.haml
%ul.nav.nav-tabs
  %li.active= link_to('transfert', '#transfert', 'data-toggle' => 'tab')
  %li= link_to('bancontact', '#bancontact', 'data-toggle' => 'tab')
  %li= link_to('Credit Card', '#credit_card', 'data-toggle' => 'tab')
.tab-content
  #transfert.tab-pane.active
    Il reste #{@user.total_wallets_in_cents/100}€ sur votre portefeuille virtuel.
    - if(@lesson.price > @user.total_wallets_in_cents)
      Ce montant n'est pas suffisant pour payer le cours. Veuillez sélectionner un autre mode de payement.
    - else
      Le montant du cours est de #{@lesson.price}€
      Après le transfer, il vous restera donc #{(@user.total_wallets_in_cents/100 - @lesson.price)}€.

    = button_to 'Ok', user_lesson_requests_payment_path(@teacher, mode: 'transfert'), remote: true, method: 'put'
    = link_to 'retour', new_user_lesson_request_path(@teacher), remote: true

  #bancontact.tab-pane
    En cliquant sur 'ok', vous serez redirigé vers votre insitution bancaire pour procéder au payement.
    = button_to 'Ok', user_lesson_requests_payment_path(@teacher, mode: 'bancontact'), remote: true, method: 'put'
    = link_to 'retour', new_user_lesson_request_path(@teacher), remote: true

  #credit_card.tab-pane
    %p Paiement par carte de crédit.
    .field.credit_card_choice
    = form_tag  user_lesson_requests_payment_path(@teacher), :method => :put, remote: true do |f|
      = hidden_field :mode, 'cd'
      = label_tag "Choisir carte"
      = select_tag :card_id, options_for_select(current_user.mangopay.cards.map { |f| [f.alias, f.id] }), {include_blank: 'Nouvelle carte'}
    #new_card
      = render 'mangopay/card_form', remote: true, no_actions: true
    .actions
      = submit_tag "Envoyer"
      = link_to 'retour', new_user_lesson_request_path(@teacher), remote: true

app/views/lesson_requests/_please_wait.html.haml
%i.fa.fa-spin.fa-spinner.fa-2x

app/views/lesson_requests/errors.js.erb
$('.lesson-request-errors').remove();
$('<div class="lesson-request-errors">').html("<%= j render('shared/errors', object: object) %>").prependTo('#lesson-details');
$('#lesson-details').trigger('update')

app/views/lesson_requests/finish.js.erb
$('#lesson-details').html("<%= j render(:partial => 'finish') %>").trigger('update');

app/views/lesson_requests/mango_account.js.erb
$('#lesson-details').html("<%= j render('mango_account') %>").trigger('update');

app/views/lesson_requests/new.haml
%h2 Réserver un cours avec #{@teacher.name}
#lesson-details
  = render partial: 'form', locals: {remote: false}

:javascript
  $(document).ready(function(){
    $('#lesson-details').trigger('update');
    new RequestLesson( $('#lesson-details'), {teacher_id: #{@teacher.id}} );
    $('#datetimepicker').datetimepicker({
      locale: moment.locale(),
      format: "L LT",
      minDate: moment("#{Time.current.beginning_of_hour + ((Time.now.min / 15.0).ceil * 15).minutes}", 'L LT')
    });
  });

app/views/lesson_requests/new.js.erb
$('#lesson-details').html("<%= j render('form') %>").trigger('update');
$('#datetimepicker2').datetimepicker({
  locale: moment.locale(),
  format: "L LT",
  minDate: moment("<%= Time.current.beginning_of_hour + ((Time.now.min / 15.0).ceil * 15).minutes %>", 'L LT')
});

app/views/lesson_requests/payment.js.erb
$('#lesson-details').html("<%= j render(:partial => '/lesson_requests/payment') %>").trigger('update');

app/views/lesson_requests/payment_method.js.erb
$('#lesson-details').html("<%= j render(:partial => '/lesson_requests/payment_method') %>").trigger('update');

mangoPay.cardRegistration.baseURL = "<%= MangoPay.configuration.root_url %>";
mangoPay.cardRegistration.clientId = "<%= MangoPay.configuration.client_id %>";

new CardRegistrationForm( $('#credit_card'), {
  card_registration_url: "<%= @card_registration.card_registration_url %>",
  card_registration_id: "<%= @card_registration.id %>",
  payment_url: "<%= user_lesson_requests_payment_path(@teacher, mode: 'cd', card_id: '__CARD_ID__').html_safe %>"
});